# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lit_author', models.CharField(max_length=250)),
                ('lit_title', models.CharField(max_length=1000)),
                ('lit_genre', models.CharField(max_length=100)),
                ('lit_file_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lit_type_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='lit',
            name='lit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.LitType'),
        ),
    ]
