# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171007_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lit',
            new_name='Literature',
        ),
    ]
