# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20171007_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='lit_file_type',
            new_name='lit_file',
        ),
    ]
