# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_literaturetype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='lit_desc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='lit_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
